import test from 'node:test';
import assert from 'node:assert/strict';
import { deriveOrmProjection, selectPublic, buildArtifacts, OrmDeriveError } from '../src/orm-derived/index.mjs';
const diesel=`diesel::table! { use diesel::sql_types::*; use crate::sql_types::*; users (id) { id -> Uuid, email -> Text, display_name -> Nullable<Text>, status -> crate::sql_types::UserStatus, created_at -> Timestamptz, } }`;
const sea=`#[derive(DeriveActiveEnum)] pub enum UserStatus { #[sea_orm(string_value = "active")] Active, #[sea_orm(string_value = "disabled")] Disabled, } pub mod user { #[sea_orm(table_name = "users")] pub struct Model { #[sea_orm(primary_key, auto_increment = false)] pub id: Uuid, pub email: String, pub display_name: Option<String>, pub status: UserStatus, pub created_at: DateTimeWithTimeZone, } }`;
test('derives validators from agreeing Diesel and SeaORM',()=>{const ir=deriveOrmProjection({dieselSource:diesel,seaOrmSource:sea,namespace:'example'}),pub=selectPublic(ir,{namespace:'example.public',models:{User:{name:'UserPublic',fields:['id','email','display_name','status']}}}),a=buildArtifacts(pub);assert.match(a['rust/src/lib.rs'],/deny_unknown_fields/);assert.match(a['typescript/index.ts'],/z\.object/);assert.match(a['dart/lib/validators.dart'],/validateUserPublic/);assert.match(a['gleam/src/orm_derived.gleam'],/user_public_decoder/);const s=JSON.parse(a['json-schema/public.schema.json']);assert.deepEqual(s.$defs.UserPublic.properties.status.enum,['active','disabled'])});
test('supports time::OffsetDateTime used by existing orm-core repos',()=>{const d=`diesel::table! { account (id) { id -> Uuid, created_at -> Timestamptz, } }`;const s=`pub mod account { #[sea_orm(table_name = "account")] pub struct Model { #[sea_orm(primary_key, auto_increment = false)] pub id: Uuid, pub created_at: OffsetDateTime, } }`;const ir=deriveOrmProjection({dieselSource:d,seaOrmSource:s});assert.equal(ir.models[0].fields[1].type,'utcDateTime')});
test('fails closed on ORM drift',()=>assert.throws(()=>deriveOrmProjection({dieselSource:diesel.replace('email -> Text','email -> Int8'),seaOrmSource:sea}),OrmDeriveError));
test('requires explicit public field allowlists',()=>{const ir=deriveOrmProjection({dieselSource:diesel,seaOrmSource:sea});assert.throws(()=>selectPublic(ir,{models:{User:{fields:[]}}}),/allowlist/)});
