import { OrmDeriveError } from './parse.mjs';
const snake=s=>String(s).replace(/([a-z0-9])([A-Z])/g,'$1_$2').replace(/[-\s]+/g,'_').toLowerCase();
const pascal=s=>String(s).replace(/(^|[_\-\s]+)([a-zA-Z0-9])/g,(_,a,c)=>c.toUpperCase());
function js(f,enums){let s;switch(f.type){case'string':s={type:'string'};break;case'uuid':s={type:'string',format:'uuid'};break;case'int32':s={type:'integer',minimum:-2147483648,maximum:2147483647};break;case'int64':s={type:'integer'};break;case'float64':s={type:'number'};break;case'boolean':s={type:'boolean'};break;case'utcDateTime':s={type:'string',format:'date-time'};break;case'plainDate':s={type:'string',format:'date'};break;case'bytes':s={type:'string',contentEncoding:'base64'};break;case'json':s={};break;case'enum':s={enum:enums[f.enumName]};break;default:throw new OrmDeriveError(`unsupported ${f.type}`)}if(f.array)s={type:'array',items:s};if(f.nullable)s={anyOf:[s,{type:'null'}]};return s}
export function emitJsonSchema(ir){const defs={};for(const m of ir.models)defs[m.name]={type:'object',additionalProperties:false,required:m.fields.filter(f=>!f.nullable).map(f=>f.name),properties:Object.fromEntries(m.fields.map(f=>[f.name,js(f,ir.enums)]))};return JSON.stringify({$schema:'https://json-schema.org/draft/2020-12/schema',$id:`urn:ores:orm-derived:${ir.namespace}`,title:`${ir.namespace} ORM-derived public projection`,$defs:defs},null,2)+'\n'}
function rt(f){let t={string:'String',uuid:'uuid::Uuid',int32:'i32',int64:'i64',float64:'f64',boolean:'bool',utcDateTime:'chrono::DateTime<chrono::Utc>',plainDate:'chrono::NaiveDate',bytes:'Vec<u8>',json:'serde_json::Value',enum:f.enumName}[f.type];if(!t)throw new OrmDeriveError(`unsupported Rust ${f.type}`);if(f.array)t=`Vec<${t}>`;if(f.nullable)t=`Option<${t}>`;return t}
export function emitRust(ir){const o=['// GENERATED from parity-checked Diesel + SeaORM definitions. Do not edit.','#![allow(dead_code)]',''];for(const[n,vals]of Object.entries(ir.enums)){o.push('#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]',`pub enum ${n} {`);for(const v of vals)o.push(`    #[serde(rename = ${JSON.stringify(v)})]`,`    ${pascal(v)},`);o.push('}','')}for(const m of ir.models){o.push('#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]','#[serde(deny_unknown_fields)]',`pub struct ${m.name} {`);for(const f of m.fields)o.push(`    pub ${snake(f.name)}: ${rt(f)},`);o.push('}','',`pub fn parse_${snake(m.name)}(json: &str) -> Result<${m.name}, serde_json::Error> {`,'    serde_json::from_str(json)','}','')}return o.join('\n')}
function z(f){let x={string:'z.string()',uuid:'z.string().uuid()',int32:'z.number().int().min(-2147483648).max(2147483647)',int64:'z.number().int()',float64:'z.number().finite()',boolean:'z.boolean()',utcDateTime:'z.string().datetime({ offset: true })',plainDate:'z.string().regex(/^\\d{4}-\\d{2}-\\d{2}$/)',bytes:'z.string()',json:'z.unknown()',enum:`z.enum(${f.enumName}Values)`}[f.type];if(!x)throw new OrmDeriveError(`unsupported Zod ${f.type}`);if(f.array)x=`z.array(${x})`;if(f.nullable)x+= '.nullable()';return x}
export function emitTs(ir){const o=["// GENERATED from parity-checked Diesel + SeaORM definitions. Do not edit.","import { z } from 'zod';",''];for(const[n,v]of Object.entries(ir.enums))o.push(`export const ${n}Values = ${JSON.stringify(v)} as const;`,`export const ${n}Schema = z.enum(${n}Values);`,`export type ${n} = z.infer<typeof ${n}Schema>;`,'');for(const m of ir.models){o.push(`export const ${m.name}Schema = z.object({`);for(const f of m.fields)o.push(`  ${JSON.stringify(f.name)}: ${z(f)},`);o.push('}).strict();',`export type ${m.name} = z.infer<typeof ${m.name}Schema>;`,'')}return o.join('\n')}
function dartCheck(f,e,enums){let x;switch(f.type){case'string':x=`${e} is String`;break;case'uuid':x=`${e} is String && RegExp(r'^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}\\$').hasMatch(${e})`;break;case'int32':x=`${e} is int && ${e} >= -2147483648 && ${e} <= 2147483647`;break;case'int64':x=`${e} is int`;break;case'float64':x=`${e} is num`;break;case'boolean':x=`${e} is bool`;break;case'utcDateTime':x=`${e} is String && DateTime.tryParse(${e}) != null`;break;case'plainDate':x=`${e} is String && RegExp(r'^\\d{4}-\\d{2}-\\d{2}\\$').hasMatch(${e})`;break;case'bytes':x=`${e} is String`;break;case'json':x='true';break;case'enum':x=`${e} is String && const ${JSON.stringify(enums[f.enumName])}.contains(${e})`;break;default:throw new OrmDeriveError(`unsupported Dart ${f.type}`)}if(f.array)x=`${e} is List && ${e}.every((v) => ${dartCheck({...f,array:false,nullable:false},'v',enums)})`;if(f.nullable)x=`${e} == null || (${x})`;return x}
export function emitDart(ir){const o=['// GENERATED from parity-checked Diesel + SeaORM definitions. Do not edit.',''];for(const m of ir.models){o.push(`Map<String, dynamic> validate${m.name}(Object? value) {`,`  if (value is! Map<String, dynamic>) throw const FormatException('${m.name} must be an object');`,`  const allowed = <String>{${m.fields.map(f=>JSON.stringify(f.name)).join(', ')}};`,'  if (value.keys.any((k) => !allowed.contains(k))) throw const FormatException(\'unknown field\');');for(const f of m.fields){if(!f.nullable)o.push(`  if (!value.containsKey(${JSON.stringify(f.name)})) throw const FormatException('missing ${f.name}');`);o.push(`  if (value.containsKey(${JSON.stringify(f.name)}) && !(${dartCheck(f,`value[${JSON.stringify(f.name)}]`,ir.enums)})) throw const FormatException('invalid ${f.name}');`)}o.push('  return value;','}','')}return o.join('\n')}
function gt(f){let t={string:'String',uuid:'String',int32:'Int',int64:'Int',float64:'Float',boolean:'Bool',utcDateTime:'String',plainDate:'String',bytes:'String',json:'Dynamic',enum:'String'}[f.type];if(f.array)t=`List(${t})`;if(f.nullable)t=`Option(${t})`;return t}
function gd(f){let d={string:'decode.string',uuid:'decode.string',int32:'decode.int',int64:'decode.int',float64:'decode.float',boolean:'decode.bool',utcDateTime:'decode.string',plainDate:'decode.string',bytes:'decode.string',json:'decode.dynamic',enum:`${snake(f.enumName)}_decoder()`}[f.type];if(!d)throw new OrmDeriveError(`unsupported Gleam ${f.type}`);if(f.array)d=`decode.list(${d})`;if(f.nullable)d=`decode.optional(${d})`;return d}
export function emitGleam(ir){const o=['// GENERATED from parity-checked Diesel + SeaORM definitions. Do not edit.','import gleam/dynamic.{type Dynamic}','import gleam/dynamic/decode','import gleam/option.{type Option}',''];for(const[n,vals]of Object.entries(ir.enums)){o.push(`fn ${snake(n)}_decoder() -> decode.Decoder(String) {`,'  use value <- decode.then(decode.string)','  case value {');for(const v of vals)o.push(`    ${JSON.stringify(v)} -> decode.success(value)`);o.push(`    _ -> decode.failure("", expected: ${JSON.stringify(n)})`,'  }','}','')}for(const m of ir.models){o.push(`pub type ${m.name} {`,`  ${m.name}(`);for(const f of m.fields)o.push(`    ${snake(f.name)}: ${gt(f)},`);o.push('  )','}','',`pub fn ${snake(m.name)}_decoder() -> decode.Decoder(${m.name}) {`);for(const f of m.fields)o.push(`  use ${snake(f.name)} <- decode.field(${JSON.stringify(f.name)}, ${gd(f)})`);o.push(`  decode.success(${m.name}(`);for(const f of m.fields)o.push(`    ${snake(f.name)}: ${snake(f.name)},`);o.push('  ))','}','')}return o.join('\n')}
export function buildArtifacts(ir){return{'orm-projection.json':JSON.stringify(ir,null,2)+'\n','json-schema/public.schema.json':emitJsonSchema(ir),'rust/src/lib.rs':emitRust(ir),'typescript/index.ts':emitTs(ir),'dart/lib/validators.dart':emitDart(ir),'gleam/src/orm_derived.gleam':emitGleam(ir)}}
