export class OrmDeriveError extends Error {}
const D={Uuid:'uuid',Text:'string',Varchar:'string',VarChar:'string',Int4:'int32',Integer:'int32',Int8:'int64',BigInt:'int64',Float8:'float64',Double:'float64',Bool:'boolean',Boolean:'boolean',Timestamptz:'utcDateTime',Date:'plainDate',Bytea:'bytes',Jsonb:'json',Json:'json'};
const R={String:'string',Uuid:'uuid',i32:'int32',i64:'int64',f64:'float64',bool:'boolean',DateTimeWithTimeZone:'utcDateTime',OffsetDateTime:'utcDateTime','time::OffsetDateTime':'utcDateTime',NaiveDate:'plainDate','chrono::NaiveDate':'plainDate','serde_json::Value':'json'};
const pascal=s=>String(s).replace(/^r#/,'').replace(/(^|[_\-\s]+)([a-zA-Z0-9])/g,(_,a,c)=>c.toUpperCase());
function body(src,open){let d=0,q=null,e=false;for(let i=open;i<src.length;i++){const c=src[i];if(q){if(e)e=false;else if(c==='\\')e=true;else if(c===q)q=null;continue}if(c==='"'||c==="'"){q=c;continue}if(c==='{')d++;else if(c==='}'&&--d===0)return src.slice(open+1,i)}throw new OrmDeriveError('unbalanced Rust block')}
function unwrap(t,w){t=t.trim();const p=w+'<';return t.startsWith(p)&&t.endsWith('>')?t.slice(p.length,-1).trim():null}
function dieselType(raw){let t=raw.replace(/\s+/g,''),nullable=false,array=false,x=unwrap(t,'Nullable');if(x!==null){nullable=true;t=x}x=unwrap(t,'Array');if(x!==null){array=true;t=x}if(!nullable&&(x=unwrap(t,'Nullable'))!==null){nullable=true;t=x}const leaf=t.split('::').at(-1),type=D[leaf];return type?{type,nullable,array}:{type:'enum',enumName:pascal(leaf),nullable,array}}
function rustType(raw){let t=raw.trim().replace(/\s+/g,''),nullable=false,array=false,x=unwrap(t,'Option');if(x!==null){nullable=true;t=x}x=unwrap(t,'Vec');if(x!==null){if(x==='u8')return{type:'bytes',nullable,array:false};array=true;t=x}const type=R[t]||R[t.replace(/^chrono::/,'')];return type?{type,nullable,array}:{type:'enum',enumName:pascal(t.split('::').at(-1)),nullable,array}}
function attr(attrs,name){return attrs.match(new RegExp(`#\\[${name}\\s*=\\s*"([^"]+)"\\]`))?.[1]??null}
export function parseDiesel(source){const models=[];for(const m of source.matchAll(/diesel::table!\s*\{/g)){const open=source.indexOf('{',m.index),b=body(source,open),h=b.match(/(?:use[^;]+;\s*)*([A-Za-z0-9_#]+)\s*\(([^)]*)\)\s*\{/);if(!h)throw new OrmDeriveError('bad diesel table header');const table=h[1].replace(/^r#/,'');const bo=b.indexOf('{',h.index+h[0].length-1),bb=body(b,bo),fields=[];for(const f of bb.matchAll(/((?:\s*#\[[^\]]+\]\s*)*)([A-Za-z0-9_#]+)\s*->\s*([^,]+),/g)){const id=f[2].replace(/^r#/,'');const column=attr(f[1]||'','sql_name')||id;fields.push({name:column,column,...dieselType(f[3])})}if(!fields.length)throw new OrmDeriveError(`no Diesel fields for ${table}`);models.push({name:pascal(table),table,primaryKey:h[2].split(',').map(x=>x.trim().replace(/^r#/,'')).filter(Boolean),fields})}if(!models.length)throw new OrmDeriveError('no diesel::table! definitions');return{models}}
function moduleBefore(src,pos){const p=src.slice(0,pos);let last=null;for(const m of p.matchAll(/pub\s+mod\s+([A-Za-z0-9_#]+)\s*\{/g))last=m[1];return last?.replace(/^r#/,'')}
export function parseSeaOrm(source){const enums={};for(const m of source.matchAll(/pub\s+enum\s+([A-Za-z0-9_]+)\s*\{/g)){if(!source.slice(Math.max(0,m.index-500),m.index).includes('DeriveActiveEnum'))continue;const b=body(source,source.indexOf('{',m.index));const vals=[...b.matchAll(/#\[sea_orm\(string_value\s*=\s*"([^"]+)"\)\]/g)].map(x=>x[1]);if(vals.length)enums[m[1]]=vals}const models=[];for(const m of source.matchAll(/#\[sea_orm\(table_name\s*=\s*"([^"]+)"\)\]\s*pub\s+struct\s+Model\s*\{/g)){const table=m[1],b=body(source,source.indexOf('{',m.index)),fields=[],primaryKey=[];for(const f of b.matchAll(/((?:\s*#\[[^\]]+\]\s*)*)pub\s+([A-Za-z0-9_#]+)\s*:\s*([^,]+),/g)){const attrs=f[1]||'',id=f[2].replace(/^r#/,'');const column=attrs.match(/column_name\s*=\s*"([^"]+)"/)?.[1]||id;if(/primary_key/.test(attrs))primaryKey.push(column);fields.push({name:column,column,...rustType(f[3])})}if(!fields.length)throw new OrmDeriveError(`no SeaORM fields for ${table}`);models.push({name:pascal(moduleBefore(source,m.index)||table),table,primaryKey,fields})}if(!models.length)throw new OrmDeriveError('no SeaORM entities');return{models,enums}}
const shape=f=>({type:f.type,enumName:f.enumName??null,nullable:!!f.nullable,array:!!f.array});
export function deriveOrmProjection({dieselSource,seaOrmSource,namespace='orm.derived'}){const d=parseDiesel(dieselSource),s=parseSeaOrm(seaOrmSource),sm=new Map(s.models.map(x=>[x.table,x])),findings=[],models=[];for(const dm of d.models){const m=sm.get(dm.table);if(!m){findings.push(`${dm.table}: missing SeaORM entity`);continue}const sf=new Map(m.fields.map(x=>[x.column,x]));for(const f of dm.fields){const o=sf.get(f.column);if(!o)findings.push(`${dm.table}.${f.column}: missing SeaORM field`);else if(JSON.stringify(shape(f))!==JSON.stringify(shape(o)))findings.push(`${dm.table}.${f.column}: type mismatch`)}for(const f of m.fields)if(!dm.fields.some(x=>x.column===f.column))findings.push(`${dm.table}.${f.column}: missing Diesel field`);if(JSON.stringify([...dm.primaryKey].sort())!==JSON.stringify([...m.primaryKey].sort()))findings.push(`${dm.table}: primary key mismatch`);models.push({name:m.name,table:dm.table,primaryKey:[...dm.primaryKey].sort(),fields:dm.fields})}for(const m of s.models)if(!d.models.some(x=>x.table===m.table))findings.push(`${m.table}: missing Diesel table`);if(findings.length)throw new OrmDeriveError('Diesel/SeaORM projection mismatch:\n- '+findings.join('\n- '));for(const m of models)for(const f of m.fields)if(f.type==='enum'&&!s.enums[f.enumName])throw new OrmDeriveError(`enum ${f.enumName} lacks SeaORM string_value metadata`);return{schema:'ores.orm-derived-projection/v1',namespace,enums:s.enums,models}}
export function selectPublic(ir,policy){if(!policy?.models||typeof policy.models!=='object')throw new OrmDeriveError('public policy must define models');const out={schema:ir.schema,namespace:policy.namespace||ir.namespace,enums:{},models:[]};for(const [k,cfg] of Object.entries(policy.models)){const m=ir.models.find(x=>x.name===k||x.table===k);if(!m)throw new OrmDeriveError(`unknown public model ${k}`);if(!Array.isArray(cfg.fields)||!cfg.fields.length)throw new OrmDeriveError(`public model ${k} needs a non-empty fields allowlist`);const fields=cfg.fields.map(n=>{const f=m.fields.find(x=>x.name===n||x.column===n);if(!f)throw new OrmDeriveError(`unknown public field ${k}.${n}`);if(f.enumName)out.enums[f.enumName]=ir.enums[f.enumName];return{...f}});out.models.push({...m,name:cfg.name||m.name,fields,primaryKey:m.primaryKey.filter(pk=>fields.some(f=>f.column===pk))})}return out}
