import { SCALARS } from '../ir.mjs';

export const snake = (s) => s.replace(/([a-z0-9])([A-Z])/g, '$1_$2').replace(/[-\s]+/g, '_').toLowerCase();
export const pascal = (s) => s.replace(/(^|[_\-\s]+)([a-zA-Z0-9])/g, (_, __, c) => c.toUpperCase());
export const camel = (s) => { const p = pascal(s); return p[0].toLowerCase() + p.slice(1); };
const HEADER = (lane, tool) => `// GENERATED by ores-contracts from the ${lane} authority — do not edit. ${tool ? `(${tool})` : ''}`.trimEnd();

function enumTypeName(m, f) { return f.enumName; }
function sqlEnumTypeName(f) { return snake(f.enumName); }

// ---------- SQL (PostgreSQL) ----------
export function emitSql(c, lane) {
  const out = [`-- GENERATED by ores-contracts from the ${lane} authority — do not edit.`, `-- namespace ${c.namespace}`, ''];
  for (const [name, values] of Object.entries(c.enums)) {
    out.push(`CREATE TYPE ${snake(name)} AS ENUM (${values.map((v) => `'${v.replace(/'/g, "''")}'`).join(', ')});`);
  }
  if (Object.keys(c.enums).length) out.push('');
  const fks = [];
  for (const m of c.models) {
    const cols = m.fields.map((f) => {
      const base = f.enumName ? sqlEnumTypeName(f) : SCALARS[f.type].sql;
      const t = f.array ? `${base}[]` : base;
      const parts = [`  ${snake(f.name)} ${t}`];
      if (!f.nullable) parts.push('NOT NULL');
      if (f.maxLength && !f.array && f.type === 'string') parts.push(`CHECK (char_length(${snake(f.name)}) <= ${f.maxLength})`);
      return parts.join(' ');
    });
    cols.push(`  PRIMARY KEY (${m.primaryKey.map(snake).join(', ')})`);
    for (const u of m.unique) cols.push(`  UNIQUE (${u.map(snake).join(', ')})`);
    out.push(`CREATE TABLE ${m.table} (\n${cols.join(',\n')}\n);`);
    for (const [i, idx] of m.indexes.entries()) out.push(`CREATE INDEX ${m.table}_idx_${i + 1} ON ${m.table} (${idx.map(snake).join(', ')});`);
    for (const f of m.fields) if (f.references) {
      const target = c.models.find((x) => x.name === f.references.model);
      fks.push(`ALTER TABLE ${m.table} ADD CONSTRAINT ${m.table}_${snake(f.name)}_fkey FOREIGN KEY (${snake(f.name)}) REFERENCES ${target.table} (${snake(f.references.field)});`);
    }
    out.push('');
  }
  if (fks.length) out.push(...fks, '');
  return out.join('\n');
}

// ---------- Rust plain types (serde) ----------
function rustType(f, forSeaOrm = false) {
  let t = f.enumName ? f.enumName : (forSeaOrm && f.type === 'utcDateTime' ? 'DateTimeWithTimeZone' : SCALARS[f.type].rust);
  if (f.array) t = `Vec<${t}>`;
  if (f.nullable) t = `Option<${t}>`;
  return t;
}
function rustEnums(c, derive) {
  return Object.entries(c.enums).map(([name, values]) => {
    const variants = values.map((v) => `    #[serde(rename = "${v}")]\n    ${pascal(v)},`).join('\n');
    return `#[derive(${derive})]\npub enum ${name} {\n${variants}\n}`;
  }).join('\n\n');
}
export function emitRust(c, lane) {
  const enums = rustEnums(c, 'Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize');
  const models = c.models.map((m) => {
    const fields = m.fields.map((f) => `    pub ${snake(f.name)}: ${rustType(f)},`).join('\n');
    return `#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]\n#[serde(deny_unknown_fields, rename_all = "camelCase")]\npub struct ${m.name} {\n${fields}\n}`;
  }).join('\n\n');
  return `${HEADER(lane)}\n// namespace ${c.namespace}\n#![allow(dead_code)]\n\n${enums}${enums ? '\n\n' : ''}${models}\n`;
}

// ---------- SeaORM entities (code-first lane) ----------
export function emitSeaOrm(c, lane) {
  const enums = Object.entries(c.enums).map(([name, values]) => {
    const variants = values.map((v) => `    #[sea_orm(string_value = "${v}")]\n    ${pascal(v)},`).join('\n');
    return `#[derive(Debug, Clone, Copy, PartialEq, Eq, EnumIter, DeriveActiveEnum, serde::Serialize, serde::Deserialize)]\n#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "${snake(name)}")]\npub enum ${name} {\n${variants}\n}`;
  }).join('\n\n');
  const mods = c.models.map((m) => {
    const fields = m.fields.map((f) => {
      const attrs = [];
      if (m.primaryKey.includes(f.name)) attrs.push('primary_key', 'auto_increment = false');
      if (f.type === 'json') attrs.push('column_type = "JsonBinary"');
      if (f.type === 'string' && f.maxLength && !f.array) attrs.push(`column_type = "Text"`);
      const attr = attrs.length ? `        #[sea_orm(${attrs.join(', ')})]\n` : '';
      return `${attr}        pub ${snake(f.name)}: ${rustType(f, true)},`;
    }).join('\n');
    const relsList = m.fields.filter((f) => f.references).map((f) => {
      const t = c.models.find((x) => x.name === f.references.model);
      return `        #[sea_orm(belongs_to = "super::${snake(t.name)}::Entity", from = "Column::${pascal(f.name)}", to = "super::${snake(t.name)}::Column::${pascal(f.references.field)}")]\n        ${t.name},`;
    }).join('\n');
    const rels = relsList ? `\n${relsList}\n    ` : '';
    return `pub mod ${snake(m.name)} {\n    use sea_orm::entity::prelude::*;\n    use super::*;\n\n    #[derive(Clone, Debug, PartialEq, DeriveEntityModel, serde::Serialize, serde::Deserialize)]\n    #[sea_orm(table_name = "${m.table}")]\n    pub struct Model {\n${fields}\n    }\n\n    #[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]\n    pub enum Relation {${rels}}\n\n    impl ActiveModelBehavior for ActiveModel {}\n}`;
  }).join('\n\n');
  return `${HEADER(lane, 'sea-orm')}\n// namespace ${c.namespace}\n#![allow(dead_code, unused_imports)]\nuse sea_orm::entity::prelude::*;\n\n${enums}${enums ? '\n\n' : ''}${mods}\n`;
}

// ---------- Diesel (db-first lane: table! schema + Queryable/Insertable structs) ----------
export function emitDiesel(c, lane) {
  const sqlTypes = Object.keys(c.enums).map((name) => `    #[derive(diesel::sql_types::SqlType, diesel::query_builder::QueryId)]\n    #[diesel(postgres_type(name = "${snake(name)}"))]\n    pub struct ${pascal(name)};`).join('\n');
  const tables = c.models.map((m) => {
    const cols = m.fields.map((f) => {
      let t = f.enumName ? `crate::sql_types::${pascal(f.enumName)}` : SCALARS[f.type].diesel;
      if (f.array) t = `Array<${t}>`;
      if (f.nullable) t = `Nullable<${t}>`;
      return `            ${snake(f.name)} -> ${t},`;
    }).join('\n');
    return `    table! {\n        use diesel::sql_types::*;\n        use crate::sql_types::*;\n        ${m.table} (${m.primaryKey.map(snake).join(', ')}) {\n${cols}\n        }\n    }`;
  }).join('\n\n');
  const joins = [];
  for (const m of c.models) for (const f of m.fields) if (f.references) {
    const t = c.models.find((x) => x.name === f.references.model);
    joins.push(`    diesel::joinable!(${m.table} -> ${t.table} (${snake(f.name)}));`);
  }
  const allow = c.models.length > 1 ? `    diesel::allow_tables_to_appear_in_same_query!(${c.models.map((m) => m.table).join(', ')});` : '';
  const structs = c.models.map((m) => {
    const fields = m.fields.map((f) => `    pub ${snake(f.name)}: ${rustType(f)},`).join('\n');
    return `#[derive(Debug, Clone, PartialEq, diesel::Queryable, diesel::Selectable, diesel::Insertable, serde::Serialize, serde::Deserialize)]\n#[diesel(table_name = schema::${m.table})]\n#[diesel(check_for_backend(diesel::pg::Pg))]\npub struct ${m.name} {\n${fields}\n}`;
  }).join('\n\n');
  return `${HEADER(lane, 'diesel')}\n// namespace ${c.namespace}\n#![allow(dead_code, unused_imports)]\n\npub mod sql_types {\n${sqlTypes}\n}\n\npub mod schema {\n${tables}\n\n${joins.join('\n')}\n${allow}\n}\n\n${rustEnums(c, 'Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, diesel_derive_enum::DbEnum').replace(/#\[derive\(([^)]*)\)\]\npub enum (\w+)/g, (s, d, n) => `#[derive(${d})]\n#[ExistingTypePath = "crate::sql_types::${pascal(n)}"]\npub enum ${n}`)}\n\n${structs}\n`;
}

// ---------- TypeScript types + validator ----------
function tsType(f) {
  let t = f.enumName ? f.enumName : SCALARS[f.type].ts;
  if (f.array) t = `${t}[]`;
  if (f.nullable) t = `${t} | null`;
  return t;
}
export function emitTsTypes(c, lane) {
  const enums = Object.entries(c.enums).map(([n, v]) => `export type ${n} = ${v.map((x) => JSON.stringify(x)).join(' | ')};\nexport const ${n}Values: readonly ${n}[] = [${v.map((x) => JSON.stringify(x)).join(', ')}] as const;`).join('\n');
  const models = c.models.map((m) => `export interface ${m.name} {\n${m.fields.map((f) => `  ${f.name}${f.nullable ? '?' : ''}: ${tsType(f)};`).join('\n')}\n}`).join('\n\n');
  return `${HEADER(lane)}\n// namespace ${c.namespace}\n${enums}\n\n${models}\n\nexport declare function validate<K extends keyof Models>(model: K, value: unknown): { ok: true; value: Models[K] } | { ok: false; errors: string[] };\nexport interface Models {\n${c.models.map((m) => `  ${m.name}: ${m.name};`).join('\n')}\n}\n`;
}
export function emitTsValidator(c, lane) {
  const scalarCheck = { string: 'typeof v === "string"', uuid: 'typeof v === "string" && /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(v)', int32: 'Number.isInteger(v) && v >= -2147483648 && v <= 2147483647', int64: 'Number.isInteger(v)', float64: 'typeof v === "number" && Number.isFinite(v)', boolean: 'typeof v === "boolean"', utcDateTime: 'typeof v === "string" && !Number.isNaN(Date.parse(v))', plainDate: 'typeof v === "string" && /^\\d{4}-\\d{2}-\\d{2}$/.test(v)', bytes: 'typeof v === "string"', json: 'v !== undefined' };
  const enums = Object.entries(c.enums).map(([n, v]) => `export const ${n}Values = Object.freeze(${JSON.stringify(v)});`).join('\n');
  const specs = c.models.map((m) => `  ${m.name}: { fields: {\n${m.fields.map((f) => `    ${f.name}: { nullable: ${f.nullable}, array: ${f.array}, check: (v) => ${f.enumName ? `${f.enumName}Values.includes(v)` : scalarCheck[f.type]}${f.maxLength && f.type === 'string' ? ` && v.length <= ${f.maxLength}` : ''} },`).join('\n')}\n  } },`).join('\n');
  return `${HEADER(lane)}\n// namespace ${c.namespace}\n${enums}\n\nconst MODELS = {\n${specs}\n};\n\nexport function validate(model, value) {\n  const spec = MODELS[model];\n  if (!spec) return { ok: false, errors: [\`unknown model \${model}\`] };\n  const errors = [];\n  if (!value || typeof value !== 'object' || Array.isArray(value)) return { ok: false, errors: ['expected an object'] };\n  for (const key of Object.keys(value)) if (!(key in spec.fields)) errors.push(\`unexpected field \${key}\`);\n  for (const [name, f] of Object.entries(spec.fields)) {\n    const v = value[name];\n    if (v === undefined || v === null) { if (!f.nullable) errors.push(\`missing required field \${name}\`); continue; }\n    if (f.array) { if (!Array.isArray(v)) { errors.push(\`\${name} must be an array\`); continue; } v.forEach((item, i) => { if (!f.check(item)) errors.push(\`\${name}[\${i}] is invalid\`); }); }\n    else if (!f.check(v)) errors.push(\`\${name} is invalid\`);\n  }\n  return errors.length ? { ok: false, errors } : { ok: true, value };\n}\n\nexport const models = Object.freeze(Object.keys(MODELS));\n`;
}

// ---------- Dart ----------
function dartType(f) {
  let t = f.enumName ? f.enumName : SCALARS[f.type].dart;
  if (f.array) t = `List<${t}>`;
  if (f.nullable && !t.endsWith('?')) t = `${t}?`;
  return t;
}
export function emitDart(c, lane) {
  const enums = Object.entries(c.enums).map(([n, v]) => `enum ${n} {\n${v.map((x) => `  ${camel(x.replace(/[^A-Za-z0-9]+/g, '_'))}('${x}'),`).join('\n')}\n  ;\n  const ${n}(this.wire);\n  final String wire;\n  static ${n} fromWire(String w) => values.firstWhere((e) => e.wire == w, orElse: () => throw FormatException('unknown ${n}: \$w'));\n}`).join('\n\n');
  const models = c.models.map((m) => {
    const fields = m.fields.map((f) => `  final ${dartType(f)} ${camel(f.name)};`).join('\n');
    const ctor = m.fields.map((f) => `    ${f.nullable ? '' : 'required '}this.${camel(f.name)},`).join('\n');
    const fromJson = m.fields.map((f) => {
      const raw = `json['${f.name}']`;
      const conv = (x) => f.enumName ? `${f.enumName}.fromWire(${x} as String)` : (f.type === 'utcDateTime' || f.type === 'plainDate') ? `DateTime.parse(${x} as String)` : f.type === 'bytes' ? `List<int>.from(${x} as List)` : f.type === 'json' ? x : `${x} as ${SCALARS[f.type].dart}`;
      let expr = f.array ? `(${raw} as List).map((e) => ${conv('e')}).toList()` : conv(raw);
      if (f.nullable) expr = `${raw} == null ? null : ${expr}`;
      return `      ${camel(f.name)}: ${expr},`;
    }).join('\n');
    const toJson = m.fields.map((f) => {
      const v = camel(f.name);
      const conv = (x) => f.enumName ? `${x}.wire` : (f.type === 'utcDateTime') ? `${x}.toUtc().toIso8601String()` : f.type === 'plainDate' ? `${x}.toIso8601String().substring(0, 10)` : x;
      const expr = f.array ? `${v}${f.nullable ? '?' : ''}.map((e) => ${conv('e')}).toList()` : (f.nullable ? (conv('x') === 'x' ? v : `${v} == null ? null : ${conv(v + '!')}`) : conv(v));
      return `      '${f.name}': ${expr},`;
    }).join('\n');
    return `class ${m.name} {\n${fields}\n\n  const ${m.name}({\n${ctor}\n  });\n\n  factory ${m.name}.fromJson(Map<String, dynamic> json) => ${m.name}(\n${fromJson}\n    );\n\n  Map<String, dynamic> toJson() => {\n${toJson}\n    };\n}`;
  }).join('\n\n');
  return `${HEADER(lane)}\n// namespace ${c.namespace}\n// ignore_for_file: constant_identifier_names\n\n${enums}\n\n${models}\n`;
}

// ---------- Authority renderers (for bootstrap / shadows) ----------
export function renderTypeSpec(c, note) {
  const enums = Object.entries(c.enums).map(([n, v]) => `enum ${n} {\n${v.map((x) => `  ${pascal(x.replace(/[^A-Za-z0-9]+/g, '_'))}: "${x}",`).join('\n')}\n}`).join('\n\n');
  const models = c.models.map((m) => {
    const decos = [`@Ores.table("${m.table}")`, ...m.unique.map((u) => `@Ores.unique("${u.join(',')}")`), ...m.indexes.map((u) => `@Ores.index("${u.join(',')}")`)];
    if (m.doc) decos.unshift(`@doc("${m.doc.replace(/"/g, '\\"')}")`);
    const fields = m.fields.map((f) => {
      const d = [];
      if (m.primaryKey.includes(f.name)) d.push('@key');
      if (f.maxLength) d.push(`@maxLength(${f.maxLength})`);
      if (f.references) d.push(`@Ores.references("${f.references.model}.${f.references.field}")`);
      if (f.doc) d.push(`@doc("${f.doc.replace(/"/g, '\\"')}")`);
      const t = `${f.enumName ?? f.type}${f.array ? '[]' : ''}`;
      return `  ${d.length ? d.join(' ') + '\n  ' : ''}${f.name}${f.nullable ? '?' : ''}: ${t};`;
    }).join('\n');
    return `${decos.join('\n')}\nmodel ${m.name} {\n${fields}\n}`;
  }).join('\n\n');
  return `${note ? `// ${note}\n` : ''}import "./ores.tsp";\nusing Ores;\n\nnamespace ${c.namespace};\n\n${enums}${enums ? '\n\n' : ''}${models}\n`;
}

export function renderJsonSchema(c, note) {
  const defs = {};
  for (const [n, v] of Object.entries(c.enums)) defs[n] = { type: 'string', enum: [...v] };
  for (const m of c.models) {
    const properties = {};
    for (const f of m.fields) {
      let p;
      if (f.enumName) p = { $ref: `#/$defs/${f.enumName}` };
      else if (f.type === 'string') p = { type: 'string', ...(f.maxLength ? { maxLength: f.maxLength } : {}) };
      else if (f.type === 'uuid') p = { type: 'string', format: 'uuid' };
      else if (f.type === 'utcDateTime') p = { type: 'string', format: 'date-time' };
      else if (f.type === 'plainDate') p = { type: 'string', format: 'date' };
      else if (f.type === 'bytes') p = { type: 'string', format: 'byte' };
      else if (f.type === 'int32') p = { type: 'integer', 'x-ores-width': 32 };
      else if (f.type === 'int64') p = { type: 'integer', 'x-ores-width': 64 };
      else if (f.type === 'float64') p = { type: 'number' };
      else if (f.type === 'boolean') p = { type: 'boolean' };
      else if (f.type === 'json') p = { type: 'object', 'x-ores-json': true };
      if (f.array) p = { type: 'array', items: p };
      if (f.references) p['x-ores-references'] = `${f.references.model}.${f.references.field}`;
      if (f.doc) p.description = f.doc;
      properties[f.name] = p;
    }
    defs[m.name] = { type: 'object', additionalProperties: false, ...(m.doc ? { description: m.doc } : {}), 'x-ores-table': m.table, 'x-ores-primary-key': [...m.primaryKey], ...(m.unique.length ? { 'x-ores-unique': m.unique.map((u) => [...u]) } : {}), ...(m.indexes.length ? { 'x-ores-indexes': m.indexes.map((u) => [...u]) } : {}), required: m.fields.filter((f) => !f.nullable).map((f) => f.name), properties };
  }
  return { $schema: 'https://json-schema.org/draft/2020-12/schema', ...(note ? { $comment: note } : {}), 'x-ores-namespace': c.namespace, $defs: defs };
}

export const EMITTERS = Object.freeze({
  'sql/schema.sql': emitSql,
  'rust/types.rs': emitRust,
  'seaorm/entities.rs': emitSeaOrm,
  'diesel/schema.rs': emitDiesel,
  'typescript/types.d.ts': emitTsTypes,
  'typescript/validate.mjs': emitTsValidator,
  'dart/models.dart': emitDart,
});
